-- use this measure to create a button in your report showing the last data refresh date.  This code is for NZ DST.  Change your time zone accordingly.  
Open Power Query Editor.
Select md_ReportDates.
In the ribbon, click Home → Advanced Editor.
Paste this:
let
    current_utc_datetime = DateTimeZone.FixedUtcNow(),

    dst_start_in_utc =
        #datetimezone(
            Date.Year(DateTimeZone.RemoveZone(current_utc_datetime)),
            9,  24, 14, 0, 0, 0, 0
        ),

    dst_end_in_utc =
        #datetimezone(
            Date.Year(DateTimeZone.RemoveZone(current_utc_datetime)) + 1,
            4, 6, 14, 0, 0, 0, 0
        ),

    utc_offset =
        if current_utc_datetime >= dst_start_in_utc
        and current_utc_datetime < dst_end_in_utc
        then 13
        else 12,

    timestamp =
        DateTimeZone.SwitchZone(
            current_utc_datetime,
            utc_offset
        ),

    #"Converted to Table" =
        #table(
            {"LastRefresh"},
            {{timestamp}}
        )
in
    #"Converted to Table"

NOW CHECK THIS:
current_utc_datetime
= DateTimeZone.RemoveZone(DateTimeZone.UtcNow())
dst_start_in_utc
= Date.AddDays(Date.StartOfWeek(#date(Date.Year(current_utc_datetime),9,30), Day.Sunday),-1)
                     & #time(14,0,0)
dst_end_in_utc
= Date.AddDays(Date.StartOfWeek(#date(Date.Year(current_utc_datetime),4,7), Day.Sunday),-1)
                   & #time(14,0,0)
utc_offset
= if current_utc_datetime >= dst_start_in_utc
            or current_utc_datetime < dst_end_in_utc
        then 13
        else 12
timestamp
= DateTimeZone.SwitchZone(DateTimeZone.UtcNow(),+utc_offset,0)
Converted to Table
= #table(2,{{timestamp,utc_offset}})
Renamed Columns
= Table.RenameColumns(#"Converted to Table",{{"Column1", "timestamp"},{"Column2", "utc_offset"}})
Changed Type
= Table.TransformColumnTypes(#"Renamed Columns",{{"timestamp", type datetimezone}, {"utc_offset", Int64.Type}})

NOW MAKE A MESASURE
Report Refreshed Text = 
"Last Refreshed:⠀" & FORMAT(MIN(md_ReportDates[timestamp]), "dd/mm/yyyy h:nn:ss")

